name: Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: use Node.js
        uses: actions/setup-node@v2

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.6.0

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akihileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: $${{secrets.HEROKU_API_KEY}
          heroku_app_name: covid-travel-app-21
          heroku_email: $${{secrets.HEROKU_EMAIL_ADDRESS}}